export const FORM_INPUTS = {
  Firestore: {
    boolean: ['checkbox', 'radio', 'switch input', 'none'],
    string: [
      'text input',
      'textarea',
      'date input',
      'number input',
      'select',
      'image uploader',
      'none',
    ],
    email: ['email input', 'text input', 'none'],
    password: ['password input', 'none'],
    number: ['number input', 'stepper input', 'none'],
    array: ['checkbox', 'none'],
    timestamp: [
      'datetime input',
      'none',
    ],
    geopoint: ['none'],
    reference: ['none'],
    map: ['none'],
    null: ['none'],
  },
  Neon: {
    string: [
      'text input',
      'textarea',
      'date input',
      'number input',
      'image uploader',
      'none',
    ],
    email: ['email input', 'text input', 'none'],
    password: ['password input', 'none'],
    integer: ['number input', 'stepper input', 'none'],
    boolean: ['checkbox', 'radio', 'switch input', 'none'],
    enum: ['select', 'radio', 'none'],
    date: ['date input', 'text input', 'none'],
    time: ['time input', 'text input', 'none'],
    bigint: ['number input', 'stepper input', 'none'],
    'numeric(10,2)': ['number input', 'stepper input', 'none'],
    uuid: ['text input', 'none'],
    Point: ['none'],
    'timestamp With Time Zone': [
      'datetime input',
      'none',
    ],
    jsonb: ['none'],
    array: ['checkbox', 'none'],
  },
};
